---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openapi-collector.swagger.config.dynamic" . }}
  labels:
    app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
    helm.sh/chart: {{ include "openapi-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  swagger-config.json: |
    {
        "urls": []
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openapi-collector.nginx.config.dynamic" . }}
  labels:
    app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
    helm.sh/chart: {{ include "openapi-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  _empty.conf: ""
