---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openapi-collector.swagger.config.dynamic" . }}
  labels:
    app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
    helm.sh/chart: {{ include "openapi-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  swagger-config.json: |
    {
        "urls": [
            {
                "name": "Test",
                "url": "https://petstore.swagger.io/v2/swagger.json"
            },
            {
                "name": "Premium API",
                "url": "/premium-api/openapi.json"
            }
        ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openapi-collector.nginx.config.dynamic" . }}
  labels:
    app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
    helm.sh/chart: {{ include "openapi-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  premium-api.conf: |
    location /premium-api {
      rewrite  ^/premium-api/(.*) /$1 break;
      proxy_pass http://premium-api;
    }
