---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openapi-collector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
    helm.sh/chart: {{ include "openapi-collector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openapi-collector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image }}"
          imagePullPolicy: {{ .Values.ui.pullPolicy }}
          env:
            - name: CONFIG_URL
              value: /swagger-config.json
          ports:
            - name: ui
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui
          readinessProbe:
            httpGet:
              path: /
              port: ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: proxy
          image: dlmiddlecote/openapi-collector-proxy:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /swagger-config.json
              port: http
          readinessProbe:
            httpGet:
              path: /swagger-config.json
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: swagger-dynamic-config
              mountPath: /www/data
              readOnly: true
            - name: nginx-dynamic-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: swagger-dynamic-config
          configMap:
            name: {{ include "openapi-collector.swagger.config.dynamic" . }}
        - name: nginx-dynamic-config
          configMap:
            name: {{ include "openapi-collector.nginx.config.dynamic" . }}
