---
apiVersion: v1
kind: Service
metadata:
  name: openapi-collector
  labels:
    app: openapi-collector
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: openapi-collector