---
replicaCount: 1

swaggerUI:
  image: dlmiddlecote/openapi-collector-ui:v0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
